const SessionActionTypes = {
  JOIN_SESSION_START: 'JOIN_SESSION_START',
  JOIN_SESSION_SUCCESS: 'JOIN_SESSION_SUCCESS',
  JOIN_SESSION_FAILURE: 'JOIN_SESSION_FAILURE',
  SEND_CHAT_MESSAGE: 'SEND_CHAT_MESSAGE'
}

export default SessionActionTypes;
