const SessionActionTypes = {
  LOAD_SESSION_START: 'LOAD_SESSION_START',
  LOAD_SESSION_SUCCESS: 'LOAD_SESSION_SUCCESS',
  LOAD_SESSION_FAILURE: 'LOAD_SESSION_FAILURE',
}

export default SessionActionTypes;
