const SessionActionTypes = {
  JOIN_SESSION_START: 'JOIN_SESSION_START',
  JOIN_SESSION_SUCCESS: 'JOIN_SESSION_SUCCESS',
  JOIN_SESSION_FAILURE: 'JOIN_SESSION_FAILURE',
  SEND_CHAT_MESSAGE: 'SEND_CHAT_MESSAGE',
  RECEIVED_CHAT_MESSAGE: 'RECIEVED_CHAT_MESSAGE',
  SEND_POLL_MESSAGE: 'SEND_POLL_MESSAGE',
  RECEIVED_POLL_MESSAGE: 'RECIEVED_POLL_MESSAGE',
  SEND_VOTE_MESSAGE: 'SEND_VOTE_MESSAGE',
}

export default SessionActionTypes;
