const UserActionTypes = {
  SET_USER_NAME: 'SET_USER_NAME',
  CONNECT_USER_START: 'CONNECT_USER_START',
  CONNECT_USER_SUCCESS: 'CONNECT_USER_SUCCESS',
  CONNECT_USER_FAILURE: 'CONNECT_USER_FAILURE',
  DISCONNECT_USER_START: 'DISCONNECT_USER_START',
  DISCONNECT_USER_SUCCESS: 'DISCONNECT_USER_SUCCESS',
  DISCONNECT_USER_FAILURE: 'DISCONNECT_USER_FAILURE'
}

export default UserActionTypes;
